language: android

os: linux

sudo: false

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

before_install: chmod +x gradlew

script:  ./gradlew clean assemble verify --stacktrace
